### ISSUE TITLE
Validate Frame Range in animation, review and pointcache product type

### ISSUE THREAD

**Issue by moonyuet** [ynput/ayon-blender#25]
@moonyuet maybe outside of scope of this PR but as we will introduce ```frame range``` on each publish instance...I would like to point out that we completely lack ```Validate Frame range``` on the ```Context``` widget as in e.g. Maya host. Shouldnt we introduce it for blender too?!

Edit: we lack it also on each publish instance, which should be very useful feature to have...again not sure what that means in terms of dev time/refactoring

_Originally posted by @LiborBatek in https://github.com/ynput/ayon-blender/issues/1#issuecomment-2320779238_

**Comment by BigRoy** [comment]
This is implemented in #44.
